#!/usr/bin/env node
const split = require('split')
const batch = require('./lib/batch')
const getEntityData = require('./lib/get_entity_data')
const ops = require('./lib/ops')
const status = require('./lib/status')
const { green, grey } = require('chalk')

process.stdin
.pipe(split())
.on('data', function (line) {
  if (line[0] !== '{') return
  line = line.replace(/,$/, '')
  const entity = JSON.parse(line)
  const data = getEntityData(entity)
  batch.aggregate(ops.fromEntityData(entity.id, data), this)
  status.increment()
})
.on('close', () => {
  batch.flush()
  .then(status.done)
})
