#!/usr/bin/env bash
set -eu
mkdir -p public/images public/icons

npm run update-toc

marked ./README.md > ./assets/html/home.content.html
./scripts/assemble_home_parts > ./public/index.html

# CSS
cp ./node_modules/github-markdown-css/github-markdown.css public/github-markdown.css

# Images
cp assets/images/favicon.16x16.png public/icons/16.png
cp assets/images/favicon.32x32.png public/icons/32.png
cp assets/images/favicon.64x64.png public/icons/64.png
cp assets/images/favicon.128x128.png public/icons/128.png
cp assets/images/favicon.192x192.png public/icons/192.png
cp assets/images/favicon.ico public/favicon.ico
cp assets/images/logo_sorted.png public/logo_sorted.png
cp assets/images/logo_sorted_square.png public/images/logo_sorted_square.png

URL_BASE=$(node -p "require('config').base()")
NAME=$(node -p "require('config').metadata.name")
TITLE=$(node -p "require('config').metadata.title")
DESCRIPTION=$(node -p "require('config').metadata.description")

substitute_strings(){
  # Using '@' as expressions separator
  sed -i "s@URL_BASE@${URL_BASE}@" $1
  sed -i "s@NAME@${NAME}@" $1
  sed -i "s@TITLE@${TITLE}@" $1
  sed -i "s@DESCRIPTION@${DESCRIPTION}@" $1
}

substitute_strings public/index.html
