#!/usr/bin/env bash

load_balance(){
  name=$1
  echo -e '\e[0;34mstarting to calculate ' $name '\e[0m'
  # Being nice to other processes
  nice ./scripts/load_balance_lines "./scripts/calculate_${name}"
}

echo -e '\e[0;32mlets go!\e[0m'

# Expect the dump on stdin
cat | load_balance 'base_scores' &&
./scripts/get_ids_stream | load_balance 'network_scores' &&
./scripts/get_ids_stream | load_balance 'secondary_network_scores' &&
./scripts/get_ids_stream | load_balance 'total_scores' &&
echo -e '\e[0;32mall scores were successfully calculated\e[0m'
