#!/usr/bin/env node
const calculate = require('../lib/calculate_item_domain_score')
const getNetworkScore = require('../lib/get_network_score')

calculate({
  scoreDomain: 'secondary',
  getScore: getNetworkScore('network')
})
